answers = {
    "BULB_C_VOLTAGE_EXPLAIN_WHY2": ["Terminal 2 and the positive terminal are separated by the gap", "Terminal 2 and the positive terminal are not connected", "terminal 2 is connected to the negative battery terminal", "terminal 2 is not separated from the negative battery terminal", "Terminal 2 and the positive battery terminal are in different electrical states"],
    "BULB_C_VOLTAGE_EXPLAIN_WHY6": ["Terminal 6 and the positive terminal are connected", "Terminal 6 and the positive terminal are not separated by the gap", "Terminal 6 and the positive terminal are not separated by the gap", "terminal 6 is not connected to the negative battery terminal", "There is no gap between terminal 6 and the positive terminal", "terminal 6 is separated by a gap from the negative battery terminal", "Terminal 6 and the positive battery terminal are in the same electrical state"],
    "PARALLEL_SWITCH_EXPLAIN_Q1": ["Bulb A is still contained in a closed path with the battery.", "Bulb A is still contained in a closed path with the battery and switch Z.", "There is no path containing both switch Y and bulb A", "Switch Y and bulb A are not in the same closed path"],
    "PARALLEL_SWITCH_EXPLAIN_Q2": ["Bulb C was no longer in a closed path with the battery", "There was no longer a closed path containing Bulb C and the battery", "there is a path containing Z and C. The open switch Z creates a gap", "there is a path containing Z and C. Opening of switch Z causes the path to be open", "there is a path containing both Z and C", "a gap", "Bulb C was not in a closed path", "Bulb C was in no closed path", "There are no closed paths"],
    "SHORT_CIRCUIT_EXPLAIN_Q_2": ["The battery in 2 is not in a closed path", "there is no closed path containing the battery", "the battery is in an open path"],
    "SHORT_CIRCUIT_EXPLAIN_Q_4": ["Circuit 4 has no closed paths", "The battery in 4 is not in a closed path", "There is no closed path", "the battery is in an open path"],
    "SHORT_CIRCUIT_EXPLAIN_Q_5": ["the battery is contained in a path in which there is no bulb", "The battery is contained in a path which does not contain any other components", "The bulb is not in the closed path containing the battery", "the battery is contained in a closed path in which there is no bulb", "The battery is contained in a closed path which does not contain any other components"],
    "SHORT_CIRCUIT_X_Q": ["the battery is damaged", "there is a short circuit"],
    "SWITCH_OPEN_EXPLAIN_Q": ["the open switch creates a gap", "a gap", "there is a gap in a circuit", "the path is not closed", "there is an incomplete circuit", "there is an open path"],
    "SWITCH_TABLE_EXPLAIN_Q1": ["Bulb A was still contained in the same closed path with the battery.", "Bulb A is still contained in a closed path with the battery and switch X.", "there is no path containing both switch Y and bulb A", "Switch Y and bulb A are not in the same closed path"],
    "SWITCH_TABLE_EXPLAIN_Q2": ["Bulb B and Bulb C were still contained in the same closed path with the battery.", "no path containing both the switch X and either bulb B or bulb C", "There is a path with B and C that does not include X"],
    "SWITCH_TABLE_EXPLAIN_Q3": ["When the switch and the bulb are contained in the same path"]
}
